<a href="https://colab.research.google.com/github/anhduc0101/anhduc/blob/main/matran%2Cvector%2Ctinh_toan_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

DUC1 = [[2,1,10],[25,3,2]]

DUC = np.array(DUC1)
print(DUC)

[[ 2  1 10]
 [25  3  2]]


In [4]:
A1 = [2,4,5,6]
A = np.array(A1)

print(' Vector 4 chieu:', A)


 Vector 4 chieu: [2 4 5 6]


In [5]:

_A = [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]   
A = np.array(_A)
print("A[0, 1]:", A[0, 1]) 
print("A[:, 0]:", A[:, 0]) 
print("A[1, :]:", A[1, :]) 

A[0, 1]: 2
A[:, 0]: [1 4]
A[1, :]: [4 5 6]


In [8]:
a = [[ 2, 2, 3 ], [ 5, 5, 6 ]]
b = [[2, 3, 5], [7, 9, 21]]
a1 = np.array(a) 
b2 = np.array(b)
print("a1 + b2:", a1 + b2) 
print("a1 – b2:",a1 - b2)

a1 + b2: [[ 4  5  8]
 [12 14 27]]
a1 – b2: [[  0  -1  -2]
 [ -2  -4 -15]]
