<a href="https://colab.research.google.com/github/anhduc0101/anhduc/blob/main/NP01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np




Bai 1:

In [2]:
A = np.array([5,7,14])

print(A)

[ 5  7 14]


Bai 2

In [4]:
A = [[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8],[7,8,9],[8,9,10],[9,10,11],[10,11,12],[11,12,13],[12,13,14],[13,14,15],[14,15,1],[15,1,2]]
A1 = np.array(A)
print(A1)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15  1]
 [15  1  2]]


Bai 3

In [5]:
A = np.random.randint(1000,size=(100,1000))

print(A)

[[949 156 488 ... 313 553 369]
 [420  81 727 ... 791 966 582]
 [810 962 523 ... 674  47 238]
 ...
 [937 730 622 ... 949 809 900]
 [971 243 603 ... 559  82 185]
 [ 43  32  89 ... 610 102 570]]


Bai 4


In [17]:
OA1 = [[7],[-5],[8]]
OA = np.array(OA1)

print(OA)

[[ 7]
 [-5]
 [ 8]]


In [27]:
OA2 = np.array((7**2)+(-5**2)+(8**2))
OA3 = np.sqrt(OA2)

print(OA3)

9.38083151964686


Bai 5


In [54]:
A = np.random.randint(10,size=2)
print("A=",A)
A1 = np.array(A)
print(A1)
B = np.random.randint(10,size=2)
print("B=",B)
B1 = np.array(B)
print(B1)
print(A1@B1)

A= [5 3]
[5 3]
B= [1 5]
[1 5]
20


[array([8, 5]) array([8, 1, 6])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
